### ISSUE TITLE
Add custom parameter to checkbox

### ISSUE THREAD

**Issue by mirzadelic** [mancunianetz/Checkbox#1]
How can i add custom parameter like `name` to checkbox, so i can check which checbox is checked?

**Comment by mancunianetz** [comment]
```Checkbox``` is a subclass of ```UIButton``` so it also has a ```tag``` property which can be used to identify a checkbox.
If you don't want to use it for some reason and want to add a custom property, go to ```Checkbox``` class, and add it right under ```mDelegate``` property for example.
